// src/routes/drinktool-policy.svelte
<script lang="ts">
  const modDate: string = new Date(document.lastModified).toLocaleDateString();
</script>

<svelte:head>
  <link rel="icon" href="/drink-tool.ico" />
  <title>Privacy-Policy · DrinkTool</title>
</svelte:head>

<header>
  <p class="top">
    Last update: {modDate}
  </p>
  <h3>DrinkTool · Privacy-Policy</h3>
  <p>
    Riccardo Buzzolo built the DrinkTool app as an Ad Supported app. This
    application is provided by Riccardo Buzzolo at no cost and is intended for
    use as is.
  </p>
  <p>
    This page is used to inform visitors regarding my policies with the
    collection, use, and disclosure of Personal Information if anyone decided to
    use my application.
  </p>
</header>
<br />
<main>
  <p>
    <strong>Please read this privacy policy carefully</strong>
  </p>
  <p>
    This privacy policy governs your use of the DrinkTool app mobile application
    and/or any in-application upgrades as well as any other media form, media
    channel, mobile website or mobile application related, linked, or otherwise
    connected thereto (collectively, the "application") for mobile devices that
    was created by Riccardo Buzzolo.
  </p>
  <p>
    <strong>Caution</strong> : this application is intended for users who are at
    least 18 years old. Persons under the age of 13 are not permitted to register
    for or use the application. Any information provided or contained within or from
    this application is for entertainment purposes only and shall not be considered
    "advice" and should not be construed as medical, legal, or financial advice on
    any subject matter. Riccardo Buzzolo disclaims all liability in regard to actions
    taken or not taken based on any or all of the contents on the application. Please
    note that Riccardo Buzzolo does not necessarily endorse, and is not responsible
    for, any third-party content that may be displayed or accessed through this application.
  </p>
  <p>
    This application estimates blood alcohol content ("BAC") based on body
    weight, height, age, stomach and gender. Actual BAC may be higher or lower
    than displayed in this app due to many factors, including but not limited to
    age, food intake, speed of drinking, drink mix, hormonal factors and genetic
    factors. These factors are not taken into account by this application when
    estimating bac.
  </p>
  <p>
    Consumption of alcohol may affect persons differently and we make no
    representation or guarantee, or warrant that any person is safe or legal to
    operate any machinery, equipment, or vehicles before or after consuming any
    amount of alcohol. Any information provided or contained within or from this
    application should not be relied upon or used in any way to determine or
    estimate a person's level of intoxication or impairment due to the
    consumption of alcohol or in rendering an opinion on or making a
    determination about a person's ability to safely or legally operate any type
    of machinery, equipment, or vehicles, including but not limited to
    motor-vehicles, motorcycles, orv's, atv's, utv's snowmobiles,vessels,
    aircraft, or locomotives.
  </p>
  <p>
    Driving while impaired or intoxicated is illegal. Do not operate machinery,
    equipment or vehicles after consuming alcohol. Be aware that drivers can be
    charged with a dui / dwi / oui even if you bac is below the legal limit when
    a law enforcement officer has probable cause based on a driver's behavior.
    Users must comply with any and all local, state and / or federal laws
    regarding driving and alcohol use and consumption.
  </p>
  <p>
    Long-term, heavy alcohol use affects the whole body, leading to neurological
    damage, gastrointestinal problems, heart disease, reproductive disorders,
    cancer and death. Additionally, the psychological and social impacts of
    alcohol can be detrimental to a person's well-being.
  </p>
  <br />
  <p>
    <strong>Information Collection and Use</strong>
  </p>
  <p>
    The app does use third party services that may collect information used to
    identify you.
  </p>
  <p>
    Link to privacy policy of third party service providers used by the app:
  </p>
  <ul>
    <li>
      <a
        rel="noreferrer"
        href={`${import.meta.env.VITE_APP_GOOGLE_POLICY_URL}`}
        target="_blank"
      >
        Google Play Services
      </a>
    </li>
    <li>
      <a
        rel="noreferrer"
        href={`${import.meta.env.VITE_APP_ADMOB_POLICY_URL}`}
        target="_blank"
      >
        AdMob
      </a>
    </li>
  </ul>
  <p>
    AdMob is an advertising service provided by Google LLC or by Google Ireland
    Limited, depending on the location this Application is accessed from. In
    order to understand Google's use of Data, consult Google's partner policy.
  </p>
  <p>
    Personal Data processed: Cookies; unique device identifiers for advertising
    (Google Advertiser ID or IDFA, for example); Usage Data.
  </p>
  <p>
    Place of processing: United States – Privacy Policy – Opt Out; Ireland –
    Privacy Policy. Privacy Shield participant.
  </p>
  <br />
  <p>
    <strong>Device permissions for Personal Data access</strong>
  </p>
  <p>
    Depending on the User's specific device, this Application may request
    certain permissions that allow it to access the User's device Data as
    described below.
  </p>
  <p>
    By default, these permissions must be granted by the User before the
    respective information can be accessed. Once the permission has been given,
    it can be revoked by the User at any time. In order to revoke these
    permissions, Users may refer to the device settings or contact the Owner for
    support at the contact details provided in the present document. The exact
    procedure for controlling app permissions may be dependent on the User's
    device and software.
  </p>
  <p>
    Please note that the revoking of such permissions might impact the proper
    functioning of this Application.
  </p>
  <p>
    If User grants any of the permissions listed below, the respective Personal
    Data may be processed (i.e accessed to, modified or removed) by this
    Application.
  </p>
  <ul>
    <li>
      <p id="underline">App specific files: Internal storage</p>
      <p>
        Used for saving persistent data of the user's profile. See more
        <span
          ><a
            rel="noreferrer"
            href={`${import.meta.env.VITE_APP_INTERNAL_ACCESS_FILES_URL}`}
            target="_blank">here</a
          >.
        </span>
      </p>
    </li>
    <li>
      <p id="underline">Internet</p>
      <p>
        {"Used to show advertisements (AdMob). See more "}
        <a
          rel="noreferrer"
          href={`${import.meta.env.VITE_APP_NETWORK_ACCESS_URL}`}
          target="_blank">here</a
        >.
      </p>
    </li>
  </ul>
  <br />
  <p>
    <strong>Cookies</strong>
  </p>
  <p>
    Cookies are files with a small amount of data that are commonly used as
    anonymous unique identifiers. These are sent to your browser from the
    websites that you visit and are stored on your device's internal memory.
  </p>
  <p>This application does not use cookies.</p>
  <br />
  <p>
    <strong>Security</strong>
  </p>
  <p>
    {"Be sure to install the application from "}
    <a
      rel="noreferrer"
      href={`${import.meta.env.VITE_APP_DRINKTOOL_URL}`}
      target="_blank">Play Store</a
    >, i am not responsible for damage to your device resulting from cracked and
    pirated versions of the app.
  </p>
  <p>
    Furthermore, the application could not work properly if not installed from
    Play Store.
  </p>
  <br />
  <p>
    <strong>Contact Me</strong>
  </p>
  <p class="bottom">
    {"If you have any questions or suggestions about my Privacy Policy, do nothesitate to contact me at "}
    <a href="mailto:riccardo.buzzolo@gmail.com"> riccardo.buzzolo@gmail.com</a>.
  </p>
</main>

<style>
  ::selection {
    color: black;
    background-color: lightcoral;
  }

  :global(body) {
    display: table-cell;
    -webkit-font-smoothing: antialiased;
    background-color: white;
    font-family: "Roboto Mono", monospace;
    font-size: var(--fontSize);
    color: black;
    word-spacing: 0px;
    padding: 3rem;
  }

  :global(body)::-webkit-scrollbar {
    width: 1rem;
  }

  :global(body)::-webkit-scrollbar-track {
    background-color: #f9f9f9;
  }

  :global(body)::-webkit-scrollbar-thumb {
    background-color: darkgray;
    border-radius: 0.5rem;
    border: 4px solid transparent;
    background-clip: content-box;
  }

  :global(body)::-webkit-scrollbar-thumb:hover {
    opacity: 0.8;
  }

  main {
    padding: 0px;
  }

  .top {
    margin-top: 0;
    font-size: 80%;
  }

  .bottom {
    margin-bottom: 0;
  }

  a {
    text-decoration: none;
  }

  a:hover {
    text-decoration: underline;
  }
</style>

// src/pages/drink-tool/DrinkToolPolicy.tsx
import { useEffect } from "react";

const DrinkToolPolicy = () => {
  useEffect(() => {
    let title = document.getElementById("title");
    if (title != null) {
      title.innerHTML = "DrinkTool · Privacy-Policy";
    }
  }, []);

  return (
    <div className="dtp-div">
      <p style={{ marginTop: 0 }}>
        <sub>{`Last update: ${new Date(
          document.lastModified
        ).toDateString()}`}</sub>
      </p>
      <h3>DrinkTool · Privacy-Policy</h3>
      <p>
        Riccardo Buzzolo built the DrinkTool app as an Ad Supported app. This
        application is provided by Riccardo Buzzolo at no cost and is intended
        for use as is.
      </p>
      <p>
        This page is used to inform visitors regarding my policies with the
        collection, use, and disclosure of Personal Information if anyone
        decided to use my application.
      </p>
      <br />
      <p>
        <strong>Please read this privacy policy carefully</strong>
      </p>
      <p>
        This privacy policy governs your use of the DrinkTool app mobile
        application and/or any in-application upgrades as well as any other
        media form, media channel, mobile website or mobile application related,
        linked, or otherwise connected thereto (collectively, the "application")
        for mobile devices that was created by Riccardo Buzzolo.
      </p>
      <p>
        <strong>Caution</strong> : this application is intended for users who
        are at least 18 years old. Persons under the age of 13 are not permitted
        to register for or use the application. Any information provided or
        contained within or from this application is for entertainment purposes
        only and shall not be considered "advice" and should not be construed as
        medical, legal, or financial advice on any subject matter. Riccardo
        Buzzolo disclaims all liability in regard to actions taken or not taken
        based on any or all of the contents on the application. Please note that
        Riccardo Buzzolo does not necessarily endorse, and is not responsible
        for, any third-party content that may be displayed or accessed through
        this application.
      </p>
      <p>
        This application estimates blood alcohol content ("BAC") based on body
        weight, height, age, stomach and gender. Actual BAC may be higher or
        lower than displayed in this app due to many factors, including but not
        limited to age, food intake, speed of drinking, drink mix, hormonal
        factors and genetic factors. These factors are not taken into account by
        this application when estimating bac.
      </p>
      <p>
        Consumption of alcohol may affect persons differently and we make no
        representation or guarantee, or warrant that any person is safe or legal
        to operate any machinery, equipment, or vehicles before or after
        consuming any amount of alcohol. Any information provided or contained
        within or from this application should not be relied upon or used in any
        way to determine or estimate a person's level of intoxication or
        impairment due to the consumption of alcohol or in rendering an opinion
        on or making a determination about a person's ability to safely or
        legally operate any type of machinery, equipment, or vehicles, including
        but not limited to motor-vehicles, motorcycles, orv's, atv's, utv's
        snowmobiles,vessels, aircraft, or locomotives.
      </p>
      <p>
        Driving while impaired or intoxicated is illegal. Do not operate
        machinery, equipment or vehicles after consuming alcohol. Be aware that
        drivers can be charged with a dui / dwi / oui even if you bac is below
        the legal limit when a law enforcement officer has probable cause based
        on a driver's behavior. Users must comply with any and all local, state
        and / or federal laws regarding driving and alcohol use and consumption.
      </p>
      <p>
        Long-term, heavy alcohol use affects the whole body, leading to
        neurological damage, gastrointestinal problems, heart disease,
        reproductive disorders, cancer and death. Additionally, the
        psychological and social impacts of alcohol can be detrimental to a
        person's well-being.
      </p>
      <br />
      <p>
        <strong>Information Collection and Use</strong>
      </p>
      <div>
        <p>
          The app does use third party services that may collect information
          used to identify you.
        </p>
        <p>
          Link to privacy policy of third party service providers used by the
          app
        </p>
        <ul>
          <li>
            <a
              rel="noreferrer"
              href={process.env.REACT_APP_GOOGLE_POLICY}
              target="_blank"
            >
              Google Play Services
            </a>
          </li>
          <li>
            <a
              rel="noreferrer"
              href={process.env.REACT_APP_ADMOB_POLICY}
              target="_blank"
            >
              AdMob
            </a>
          </li>
        </ul>
        <p>
          AdMob is an advertising service provided by Google LLC or by Google
          Ireland Limited, depending on the location this Application is
          accessed from. In order to understand Google's use of Data, consult
          Google's partner policy.
        </p>
        <p>
          Personal Data processed: Cookies; unique device identifiers for
          advertising (Google Advertiser ID or IDFA, for example); Usage Data.
        </p>
        <p>
          Place of processing: United States – Privacy Policy – Opt Out; Ireland
          – Privacy Policy. Privacy Shield participant.
        </p>
      </div>
      <br />
      <p>
        <strong>Device permissions for Personal Data access</strong>
      </p>
      <p>
        Depending on the User's specific device, this Application may request
        certain permissions that allow it to access the User's device Data as
        described below.
      </p>
      <p>
        By default, these permissions must be granted by the User before the
        respective information can be accessed. Once the permission has been
        given, it can be revoked by the User at any time. In order to revoke
        these permissions, Users may refer to the device settings or contact the
        Owner for support at the contact details provided in the present
        document. The exact procedure for controlling app permissions may be
        dependent on the User's device and software.
      </p>
      <p>
        Please note that the revoking of such permissions might impact the
        proper functioning of this Application.
      </p>
      <p>
        If User grants any of the permissions listed below, the respective
        Personal Data may be processed (i.e accessed to, modified or removed) by
        this Application.
      </p>
      <ul>
        <li>
          <p id="underline">App specific files: Internal storage</p>
          <p>
            {"Used for saving persistent data of the user's profile. See more "}
            <a
              rel="noreferrer"
              href={process.env.REACT_APP_INTERNAL_ACCESS_FILES}
              target="_blank"
            >
              here
            </a>
            .
          </p>
        </li>
        <li>
          <p id="underline">Internet</p>
          <p>
            {"Used to show advertisements (AdMob). See more "}
            <a
              rel="noreferrer"
              href={process.env.REACT_APP_NETWORK_ACCESS}
              target="_blank"
            >
              here
            </a>
            .
          </p>
        </li>
      </ul>
      <br />
      <p>
        <strong>Cookies</strong>
      </p>
      <p>
        Cookies are files with a small amount of data that are commonly used as
        anonymous unique identifiers. These are sent to your browser from the
        websites that you visit and are stored on your device's internal memory.
      </p>
      <p>This application does not use cookies.</p>
      <br />
      <p>
        <strong>Security</strong>
      </p>
      <p>
        {"Be sure to install the application from "}
        <a
          rel="noreferrer"
          href={process.env.REACT_APP_DRINKTOOL_URL}
          target="_blank"
        >
          Play Store
        </a>
        , i am not responsible for damage to your device resulting from cracked
        and pirated versions of the app.
      </p>
      <p>
        Furthermore, the application could not work properly if not installed
        from Play Store.
      </p>
      <br />
      <p>
        <strong>Contact Me</strong>
      </p>
      <p style={{ marginBottom: 0 }}>
        {
          "If you have any questions or suggestions about my Privacy Policy, do nothesitate to contact me at "
        }
        <a href="mailto:riccardo.buzzolo@gmail.com">
          riccardo.buzzolo@gmail.com
        </a>
        .
      </p>
    </div>
  );
};

export default DrinkToolPolicy;
