// src/lib/components/Footer/Footer.svelte
<script lang="ts">
  import ContactLink from "./ContactLink.svelte";

  const year: number = new Date().getFullYear();
</script>

<footer>
  <div class="contacts-container">
    <ContactLink
      href={import.meta.env.VITE_APP_MAILTO}
      icon="mail"
      text="riccardo.buzzolo@gmail.com"
    />
    <ContactLink
      href={import.meta.env.VITE_APP_INSTAGRAM_PROFILE_URL}
      icon="instagram"
      text="@riccardo_buzzolo"
    />
    <ContactLink
      href={import.meta.env.VITE_APP_GITHUB_PROFILE_URL}
      icon="github"
      text="@ricbuz94"
    />
    <ContactLink
      href={import.meta.env.VITE_APP_TWITTER_PROFILE_URL}
      icon="twitter"
      text="@riccardobuzzolo"
    />
  </div>
  <p class="bottom-text">
    Made with
    <a
      class="footer-link"
      href={`${import.meta.env.VITE_APP_SVELTEKIT_URL}`}
      target="_blank"
      rel="noreferrer">SvelteKit</a
    >
    and
    <a
      class="footer-link"
      href={`${import.meta.env.VITE_APP_GITHUB_PAGES_URL}`}
      target="_blank"
      rel="noreferrer">GitHub Pages</a
    >
  </p>
  <p class="sub-text bottom-text">
    © {year} Riccardo Buzzolo. All Rights Reserved.
  </p>
</footer>

<style>
  footer {
    margin-left: auto;
    margin-right: auto;
    max-width: 70vw;
    font-size: 80%;
    min-width: 45vmin;
    padding-top: 2rem;
    padding-bottom: 6rem;
    padding-left: 20%;
    padding-right: 20%;
    transition: opacity 300ms ease;
  }

  .contacts-container {
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: space-evenly;
    margin-bottom: 3rem;
  }

  .footer-link {
    color: var(--accentColor);
    font-weight: bold;
    text-decoration: none;
    transition: color var(--transition);
  }

  .footer-link:hover {
    color: var(--accentColorHover);
  }

  p {
    line-height: 1.2;
    text-align: center;
  }

  p.sub-text {
    color: var(--subTextColor);
  }

  /* schermo piccolo */
  @media only screen and (max-width: 720px) {
    footer {
      max-width: 100vw;
      padding-bottom: 3rem;
      padding-left: 1.5rem;
      padding-right: 1.5rem;
    }

    footer a {
      width: 100%;
      text-align: center;
    }
  }

  /* schermo grande */
  @media only screen and (min-width: 1400px) {
    .contacts-container {
      margin-bottom: 5rem;
    }

    footer a p {
      display: inline;
      line-height: 2;
      padding-left: 5px;
      font-size: 1rem;
      vertical-align: top;
      color: var(--textColor);
    }

    footer a:hover p {
      color: var(--accentColor);
    }
  }
</style>

// src/components/Footer.tsx
import { FiMail, FiTwitter, FiInstagram, FiGithub } from "react-icons/fi";
import styled from "styled-components";
import FooterIcon from "../ui/FooterIcon";
import SiteLink from "../ui/SiteLink";

const StyledFooter = styled.footer`
  min-height: max-content;
  padding-top: 2rem;
  padding-bottom: 4rem;
  min-width: 45vmin;
  transition: ${(props) => props.theme.foregroundColorTransition};

  & p {
    font-size: 70%;
    text-align: center;
    line-height: 1.5;
    margin: 0;
  }

  & div {
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: space-evenly;
    margin-bottom: 2rem;
  }
`;

const Footer = () => (
  <StyledFooter>
    <div>
      <FooterIcon href={process.env.REACT_APP_MAILTO}>
        <FiMail />
      </FooterIcon>
      <FooterIcon href={process.env.REACT_APP_INSTAGRAM}>
        <FiInstagram />
      </FooterIcon>
      <FooterIcon href={process.env.REACT_APP_GITHUB}>
        <FiGithub />
      </FooterIcon>
      <FooterIcon href={process.env.REACT_APP_TWITTER}>
        <FiTwitter />
      </FooterIcon>
    </div>
    <p>
      {"Made whith "}
      <span>
        <SiteLink
          title=" Create React App"
          href="https://create-react-app.dev/"
        />
        {" and "}
        <SiteLink title="GitHub Pages" href="https://pages.github.com/" />
      </span>
    </p>
    <p>{`Riccardo Buzzolo © ${new Date().getFullYear()}`}</p>
  </StyledFooter>
);

export default Footer;
